.\"
.\" gtrm-client.1 -- this file is the short manual page for the GNU trm client.
.\"
.\" Copyright (C) 2006 Efstathios Chatzikyriakidis (contact@efxa.org)
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
.\"
.TH GTRM-CLIENT "1" "November 2006" "gtrm-client 0.1" "User Commands"

.SH NAME
gtrm-client \- manual page for GNU terminal random message client.

.SH SYNOPSIS
.B gtrm-client
[\fIOPTIONS\fR]

.SH DESCRIPTION
The GNU trm client sends a request to a GNU 
trm server for a terminal random message.

.SH OPTIONS
.TP
\-p, \-\-port `\fBport\fR'
Protocol port number server is using. (\fBoptional\fR).
.TP
\-z, \-\-host `\fBhost\fR'
Name of the computer on which the GNU trm server is executing. (\fBoptional\fR).
.TP
\-v, \-\-verbose
Explain what is being done.
.TP
\-\-help, \-\-usage
Display a short help and exit.
.TP
\-\-version
Print version information and exit.

.SH AUTHOR
Written by Efstathios Chatzikyriakidis.

.SH "REPORTING BUGS"
Report bugs to <bug-gnu-trm-client@gnu.org>.

.SH COPYRIGHT
Copyright \(co 2006 Efstathios Chatzikyriakidis (contact@efxa.org)

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH "SEE ALSO"
The full documentation for
.B gtrm-client
is maintained as a Texinfo manual. If the
.B info
and
.B gtrm-client
programs are properly installed at your site, the command
.IP
.B info gtrm-client
.PP
should give you access to the complete manual.
